create table from_host_institution (
`Dept_name` varchar(100) not null,
`Year` varchar(30) NOT NULL,
faculty_name varchar(50) not null,
primary key(Dept_name,Year,faculty_name),
foreign key(Dept_name) references Departments(Dept_name)
-- foreign key(Year) references Departments(Year)
);

insert into from_host_institution VALUES
('Computer Science And Engineering','2014-15','Ajitha S'),
('Computer Science And Engineering','2014-15','Annapurna P Patil'),
('Computer Science And Engineering','2014-15','Jagannath S'),
('Computer Science And Engineering','2014-15','Krishnaraj P M'),
('Computer Science And Engineering','2014-15','Madhu Bhan'),
('Computer Science And Engineering','2014-15','Mallegowda M'),
('Computer Science And Engineering','2014-15','Mrinalini M'),
('Computer Science And Engineering','2014-15','Seema S'),
('Computer Science And Engineering','2014-15','Shobha K R'),
('Computer Science And Engineering','2014-15','Sini Anna Alex'),

('Computer Science And Engineering','2015-16','Ajitha S'),
('Computer Science And Engineering','2015-16','Krishnaraj P M'),
('Computer Science And Engineering','2015-16','Madhu Bhan'),
('Computer Science And Engineering','2015-16','Mallegowda M'),
('Computer Science And Engineering','2015-16','Sini Anna Alex'),
('Computer Science And Engineering','2015-16','Koushik S'),
('Computer Science And Engineering','2015-16','Pramod Sunagar'),
('Computer Science And Engineering','2015-16','Suresh Kumar K R'),

('Computer Science And Engineering','2016-17','Madhu Bhan'),
('Computer Science And Engineering','2016-17','Mallegowda M'),
('Computer Science And Engineering','2016-17','Sini Anna Alex'),
('Computer Science And Engineering','2016-17','Koushik S'),
('Computer Science And Engineering','2016-17','Pramod Sunagar'),
('Computer Science And Engineering','2016-17','Suresh Kumar K R'),
('Computer Science And Engineering','2016-17','DarshanaNaik'),
('Computer Science And Engineering','2016-17','Meeradevi'),
('Computer Science And Engineering','2016-17','Pradeep Kumar D'),
('Computer Science And Engineering','2016-17','Sanjeetha. R'),
('Computer Science And Engineering','2016-17','Sowmya B J'),

('Computer Science And Engineering','2017-18','Mallegowda M'),
('Computer Science And Engineering','2017-18','Sini Anna Alex'),
('Computer Science And Engineering','2017-18','Koushik S'),
('Computer Science And Engineering','2017-18','Pramod Sunagar'),
('Computer Science And Engineering','2017-18','Suresh Kumar K R'),
('Computer Science And Engineering','2017-18','DarshanaNaik'),
('Computer Science And Engineering','2017-18','Meeradevi'),
('Computer Science And Engineering','2017-18','Pradeep Kumar D'),
('Computer Science And Engineering','2017-18','Sanjeetha. R'),
('Computer Science And Engineering','2017-18','Sowmya B J'),
('Computer Science And Engineering','2017-18','Chandrika Prasad'),
('Computer Science And Engineering','2017-18','Rajeshwari S B'),
('Computer Science And Engineering','2017-18','Savitha Shetty'),

('Computer Science And Engineering','2018-19','Mallegowda M'),
('Computer Science And Engineering','2018-19','Sini Anna Alex'),
('Computer Science And Engineering','2018-19','Koushik S'),
('Computer Science And Engineering','2018-19','Pramod Sunagar'),
('Computer Science And Engineering','2018-19','Suresh Kumar K R'),
('Computer Science And Engineering','2018-19','DarshanaNaik'),
('Computer Science And Engineering','2018-19','Meeradevi'),
('Computer Science And Engineering','2018-19','Pradeep Kumar D'),
('Computer Science And Engineering','2018-19','Sanjeetha. R'),
('Computer Science And Engineering','2018-19','Sowmya B J'),
('Computer Science And Engineering','2018-19','Chandrika Prasad'),
('Computer Science And Engineering','2018-19','Rajeshwari S B'),
('Computer Science And Engineering','2018-19','Savitha Shetty'),
('Computer Science And Engineering','2018-19','Aparna R'),
('Computer Science And Engineering','2018-19','Mamatha Jadhav V'),
('Computer Science And Engineering','2018-19','Shreekant Jere'),
('Computer Science And Engineering','2018-19','Vandana Sudhakar Sardar'),
('Computer Science And Engineering','2018-19','Veena G S');


